# Generated by Django 3.2.3 on 2021-06-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Tipo de vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('numero', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero de vehiculo')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('año', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Año')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('idRefaccion', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='ID Refaccion')),
                ('nombreRefaccion', models.CharField(max_length=10, verbose_name='Nombre refaccion')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.vehiculo')),
            ],
        ),
    ]
